#' @title Plots locations on a map
#' @description The function generates a map plotting all locations, filtered by \code{get.coordinates()}. The plot also displays additional information if used by \code{candidates.maps()}
#' @param x numeric. Latitude of locations filtered by \code{get.coordinates()}
#' @param y numeric. Longitude of locations filtered by \code{get.coordinates()}
#' @param cc character string. Country code of locations filtered by \code{get.coordinates()}
#' @param matches character string. string of each entry filtered by \code{get.coordinates()}
#' @param color character string indicating, which color is assigned to each country code in order.
#' @param strings Character strings in form of regular expression that filter the data frames. The first string is shown on the plot.
#' @param plot logical. If \code{FALSE} then the plot will not be printed but saved as .png in the current working directory.
#' @param ratio_string character string. Ratio of occurrences in the polygon from \code{top.candidates()}.
#' @param fq character string. Number of occurrences in the designated polygon and in total.
#' @importFrom dplyr %>%
#' @importFrom dplyr mutate_at
#' @importFrom rnaturalearth ne_countries
#' @import ggplot2
#' @return A plot in the current R session or as .png in the working directory. If directly generated by \code{top()}, it displays the first string and the total occurrences. If generated by \code{candidates.maps()}, it displays the string, the ratio as a percentage and the number of occurrences in the designated polygon and in total.
simple.map <- function(x, y, cc, matches, color, strings, plot, ratio_string, fq) {

  nas <- unique(which(is.na(x)), which(is.na(y))) # checks for NAs
  if ( length(nas) > 0 ) {
    x <- x[-nas]; y <- y[-nas]
  }
  if ( length(x)==0 | length(y)==0 ) {
    cat("\nThere are no coordinates to plot\n")
    return(invisible(NULL))
  }
  md <- cbind(as.numeric(x), as.numeric(y), cc, matches) %>% # creates df out of x and y coordinates
    as.data.frame() %>%
    mutate_at(c("V1", "V2"), as.numeric)


  # get max min long and lat and add a frame of 10% around the points
  lat_range <- range(md[,1])
  lng_range <- range(md[,2])
  lat_extend <- 0.1 * diff(lat_range)
  lng_extend <- 0.1 * diff(lng_range)
  lat_range <- c(lat_range - lat_extend, lat_range + lat_extend)
  lng_range <- c(lng_range - lng_extend, lng_range + lng_extend)
  #	for (i in 1:4) {
  #		if (lng_range[i] > 180) {lng_range[i] <- 180}
  #		if (lng_range[i] < -180) {lng_range[i] <- -180}
  #	}
  map <- ne_countries(scale = 50, returnclass = "sf") # gets world map from pkg "rnaturalearth"

  lengths <- as.data.frame(table(md[,4])) # frequencies of each string in the same order
  lengths <- lengths[match(gsub("[[:punct:]]", "", strings), lengths$Var1),][,2]


  # creates plot
  p <- ggplot() +
    geom_sf(data = map) +
    geom_point(data = md, mapping = aes(x = md[,2], y = md[,1], col = md[,4], shape = md[,3])) +
    coord_sf(xlim=c(min(lng_range), max(lng_range)),
             ylim=c(min(lat_range), max(lat_range))) +
    scale_color_manual(values = color) +
    labs(x = "longitude", y = "latitude", color = "country", shape = "string", title = paste(strings, lengths, collapse = "| ")) +   # legend only with string & frequency
    {if(nchar(ratio_string) > 0 && nchar(fq) > 0)labs(title = paste(strings, ratio_string, fq, collapse = " "))} # extended legend if created with candidates.maps()


  # saves or prints plot
  if (plot == FALSE) {
    plot_name <- paste0("plot_", paste(regmatches(strings, regexpr("[a-zA-Z]+", strings)), collapse = "_"),".png", collapse="_")
    ggsave(plot_name, path = file.path(getwd(), "plots"))
    cat(paste("\nPlot",plot_name ,"saved in plots folder of the working directory.\n"))
  }
  else {
    print(p)
  }
}
