#' @title Generates a map with all locations matching the regular expression
#' @description The function calls the \code{simpleMap()} function to generate a map plotting all locations, filtered by \code{getCoordinates()}. The plot also displays additional information if used by \code{topCompOut()}. The data used is downloaded by \code{getData()} and is accessible on the [GeoNames download server](https://download.geonames.org/export/dump/).
#' @param strings character strings in form of regular expression that filter the data frames.
#' @param countries character string with country code abbreviations (check \url{https://www.geonames.org/countries/} for a list of available countries) specifying, the toponyms of which countries are checked.
#' @param color character string indicating, which color is assigned to each string.
#' @param regions numeric. Specify the level of regional borders. By default \code{0} displaying only country borders.
#' @param df logical. If \code{TRUE} then the filtered data frame will be saved in the global environment.
#' @param csv logical. If \code{TRUE} then the filtered data frame will be saved as .csv in the current working directory.
#' @param plot logical. If \code{FALSE} then the plot will not be printed but saved as .png in the current working directory.
#' @param ratio_string character string. Ratio of occurrences in the polygon from \code{topComp()}. This should not be specified manually.
#' @param fq character string. Number of occurrences in the designated polygon and in total returned by \code{topComp()}. This should not be specified manually.
#' @param feat.class character string with feature classes (check \url{http://download.geonames.org/export/dump/readme.txt} for the list and names of all feature classes in the data). By default, it is \code{p}.
#' @param lons numeric. Vector of longitudinal coordinates defining the polygon.
#' @param lats numeric. Vector of latitudinal coordinates defining the polygon.
#' @examples
#' \dontrun{
#' getData("DE", save = TRUE)
#' # saves data for DE in package directory
#' top("itz$", "DE")
#' # generates and prints a map with all populated places
#' # in Germany ending with "itz"
#' # and saves the locations in a data frame in the global environment.
#'
#'
#' top("^By", "DK", color = "green", df = FALSE, csv = TRUE, plot = TRUE)
#' # first downloads data for DK and extracts it to the temporary directory
#' # generates plot with all populated places colored in green
#' # in Denmark starting with "By" (case sensitive)
#' # and saves it as .png together with the location data as .csv in the working directory.
#'
#'
#' getData(c("DE", "PL"), save = TRUE)
#' # saves for DE and PL in package directory if it's not already there
#' top(c("itz$", "ice$"), c("DE", "PL"))
#' # generates plot with all populated places in Germany colored in red and Poland colored in cyan
#' # ending with either "itz" or "ice"
#' # and saves the locations in a data frame in the global environment.
#' }
#' @return A plot in the current R session or as .png in the working directory. If directly generated by this function \code{top()}, it displays the first string and the total occurrences. If generated by \code{topCompOut()}, it displays the string, the ratio as a percentage and the number of occurrences in the designated polygon and in total.
#' @export
top <- function(strings, countries,
                color = NULL, regions = 0,
                df = TRUE, csv = FALSE, plot = TRUE,
                ratio_string = "", fq = "", feat.class = "P",
                lons, lats) {
  for (i in 1:length(countries)) {
    countries[i] <- country(query = countries[i])[, 1]
  } # converts input into ISO2 codes
  countries <- countries[!is.na(countries)] # removes incorrect country names


  getData(countries) # gets data
  gn <- readFiles(countries, feat.class) # stands for GeoNames
  coordinates <- getCoordinates(gn, strings, df, csv) # coordinates of matches
  simpleMap(coordinates, color, strings, regions, plot, ratio_string, fq, lons, lats) # inserts coordinates and generates map
}
